# src/main/resources/application.yml
spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: jdbc:p6spy:mariadb://localhost:3306/blog
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: your_db_username
    password: your_db_password

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: jkc.blog.com.mapper,jkc.blog.com.common.util
  configuration:
    map-underscore-to-camel-case: true

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  encoding: UTF-8
  cache: false

logging:
  level:
    p6spy: info
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    org.mybatis: off
    org.apache.ibatis: off

server:
  port: 8081